crm/ReallySimpleCRM/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from django.contrib.auth.views import LogoutView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contacts/', include('contacts.urls')),
    path("", include("authentication.urls")),
    path('', views.index, name='home'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm/contacts/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views


app_name = 'contacts'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:contact_id>/', views.detail, name='detail'),
    path('<int:contact_id>/edit', views.contact_edit_view, name='edit'),
    path('create', views.contact_create_view, name='create'),
    path('<int:contact_id>/postcard', views.postcard_view, name='create')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm/contacts/models.py
from django.conf import settings
from django.db import models
from django.core.validators import MaxValueValidator


class Contact(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.CharField(max_length=50, blank=True)
    address_line_1 = models.CharField(max_length=50, blank=True)
    address_line_2 = models.CharField(max_length=50, blank=True)
    city = models.CharField(max_length=50, blank=True)
    state = models.CharField(max_length=50, blank=True)
    zipcode = models.PositiveIntegerField(
        null=True, blank=True, validators=[MaxValueValidator(999999)])
    profile_picture = models.ImageField(blank=True, null=True)

    def __str__(self):
        return self.first_name + " " + self.last_name

crm/contacts/forms.py
from django import forms
from .models import Contact

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        exclude = ['user']

crm/contacts/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.core.files.storage import FileSystemStorage
from django.conf import settings
from django.db.models.functions import Lower

import os

from .models import Contact
from .forms import ContactForm
from .postcards import send_postcard
from .xls import import_contacts, export_contacts


@login_required(login_url="/login/")
def index(request):
    if request.method == 'POST' and 'document' in request.FILES:
        uploaded_file = request.FILES['document']
        fs = FileSystemStorage()
        name = fs.save(uploaded_file.name, uploaded_file)
        import_contacts(fs.url(name)[1:], request.user)
    contact_list = Contact.objects.filter(user=request.user).order_by(
        Lower('first_name'), Lower('last_name'))
    context = {'contact_list': contact_list}
    export = request.GET.get('export', False)
    if export:
        return export_contacts(request.user)
    return render(request, 'index.html', context)


@login_required(login_url="/login/")
def detail(request, contact_id):
    contact = get_object_or_404(Contact, id=contact_id)
    if request.method == 'POST':
        try:
            send_postcard(contact, request.POST['postcard_text'])
        except Exception as e:
            return render(request, 'pages/profile.html', {'contact': contact, 'postcard_error': str(e)})
        return render(request, 'pages/profile.html', {'contact': contact, 'postcard_success': True})
    return render(request, 'pages/profile.html', {'contact': contact})


@login_required(login_url="/login/")
def contact_create_view(request):
    form = ContactForm(request.POST or None, request.FILES)
    if form.is_valid():
        contact = form.save(commit=False)
        contact.user = request.user
        contact.save()
        return HttpResponseRedirect(reverse('contacts:detail', args=(contact.id,)))

    return render(request, 'pages/contact_create.html', {'form': form})


def contact_edit_view(request, contact_id):
    contact = get_object_or_404(Contact, id=contact_id)
    if request.method == "POST":
        form = ContactForm(request.POST, request.FILES, instance=contact)
        if form.is_valid():
            contact = form.save(commit=False)
            contact.user = request.user
            contact.save()
            return HttpResponseRedirect(reverse('contacts:detail', args=(contact.id,)))
    else:
        form = ContactForm(instance=contact)
    return render(request, 'pages/contact_create.html', {'form': form, 'contact': contact})


@login_required(login_url="/login/")
def postcard_view(request, contact_id):
    contact = get_object_or_404(Contact, id=contact_id)
    send_postcard(contact)
    return HttpResponseRedirect(reverse('contacts:detail', args=(contact.id,)))

crm/contacts/templates/index.html
{% extends 'layouts/base.html' %}

{% block title %} Really Simple CRM {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<!-- Header -->
<div class="header bg-gradient-primary pb-8 pt-5 pt-md-8">
  <div class="container-fluid">
    <div class="header-body">
    </div>
  </div>
</div>

<div class="container-fluid mt--7">
  <div class="row mt-5">
    <div class="col-xl-11 mb-5 mb-xl-0">
      <div class="card shadow">
        <div class="card-header border-0">
          <div class="row align-items-center">
            <div class="col">
              <h3 class="mb-0">Contacts</h3>
            </div>
            <div class="col text-center">
              <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="file" class="btn-sm" name="document">
                <button type="submit" class="btn btn-sm btn-primary">Import Contacts</button>
              </form>
            </div>
            <div class="col text-right">
              <a href="{% url 'contacts:index' %}?export=True" class="btn btn-sm btn-primary">Export Contacts</a>
              <a href="{% url 'contacts:create' %}" class="btn btn-sm btn-primary">Create Contact</a>
            </div>
          </div>
        </div>
        <div class="table-responsive">
          <!-- Projects table -->
          <table class="table align-items-center table-flush">
            <thead class="thead-light">
              <tr>
                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <th scope="col">Address Line 1</th>
                <th scope="col">Address Line 2</th>
                <th scope="col">City</th>
                <th scope="col">State</th>
                <th scope="col">Zipcode</th>
                <th scope="col"></th>
              </tr>
            </thead>
            <tbody>
              {% for contact in contact_list %}
              <tr>
                <th scope="row">
                  {{ contact  }}
                </th>
                <td>
                  {{ contact.email  }}
                </td>
                <td>
                  {{ contact.address_line_1  }}
                </td>
                <td>
                  {{ contact.address_line_2  }}
                </td>
                <td>
                  {{ contact.city  }}
                </td>
                <td>
                  {{ contact.state  }}
                </td>
                <td>
                  {{ contact.zipcode  }}
                </td>
                <td>
                  <a href="{% url 'contacts:detail' contact.id %}" class="btn btn-sm btn-primary">View / Edit</a>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

  {% if uploaded_file_url %}
  <p>File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
  {% endif %}

</div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}{% endblock javascripts %}