crm/ReallySimpleCRM/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from django.contrib.auth.views import LogoutView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contacts/', include('contacts.urls')),
    path("", include("authentication.urls")),
    path('', views.index, name='home'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm/contacts/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views


app_name = 'contacts'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:contact_id>/', views.detail, name='detail'),
    path('<int:contact_id>/edit', views.contact_edit_view, name='edit'),
    path('create', views.contact_create_view, name='create'),
    path('<int:contact_id>/postcard', views.postcard_view, name='create')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm/contacts/models.py
from django.conf import settings
from django.db import models
from django.core.validators import MaxValueValidator


class Contact(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.CharField(max_length=50, blank=True)
    address_line_1 = models.CharField(max_length=50, blank=True)
    address_line_2 = models.CharField(max_length=50, blank=True)
    city = models.CharField(max_length=50, blank=True)
    state = models.CharField(max_length=50, blank=True)
    zipcode = models.PositiveIntegerField(
        null=True, blank=True, validators=[MaxValueValidator(999999)])
    profile_picture = models.ImageField(blank=True, null=True)

    def __str__(self):
        return self.first_name + " " + self.last_name

crm/contacts/forms.py
from django import forms
from .models import Contact

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        exclude = ['user']

crm/contacts/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.core.files.storage import FileSystemStorage
from django.conf import settings
from django.db.models.functions import Lower

import os

from .models import Contact
from .forms import ContactForm
from .postcards import send_postcard
from .xls import import_contacts, export_contacts


@login_required(login_url="/login/")
def index(request):
    if request.method == 'POST' and 'document' in request.FILES:
        uploaded_file = request.FILES['document']
        fs = FileSystemStorage()
        name = fs.save(uploaded_file.name, uploaded_file)
        import_contacts(fs.url(name)[1:], request.user)
    contact_list = Contact.objects.filter(user=request.user).order_by(
        Lower('first_name'), Lower('last_name'))
    context = {'contact_list': contact_list}
    export = request.GET.get('export', False)
    if export:
        return export_contacts(request.user)
    return render(request, 'index.html', context)


@login_required(login_url="/login/")
def detail(request, contact_id):
    contact = get_object_or_404(Contact, id=contact_id)
    if request.method == 'POST':
        try:
            send_postcard(contact, request.POST['postcard_text'])
        except Exception as e:
            return render(request, 'pages/profile.html', {'contact': contact, 'postcard_error': str(e)})
        return render(request, 'pages/profile.html', {'contact': contact, 'postcard_success': True})
    return render(request, 'pages/profile.html', {'contact': contact})


@login_required(login_url="/login/")
def contact_create_view(request):
    form = ContactForm(request.POST or None, request.FILES)
    if form.is_valid():
        contact = form.save(commit=False)
        contact.user = request.user
        contact.save()
        return HttpResponseRedirect(reverse('contacts:detail', args=(contact.id,)))

    return render(request, 'pages/contact_create.html', {'form': form})


def contact_edit_view(request, contact_id):
    contact = get_object_or_404(Contact, id=contact_id)
    if request.method == "POST":
        form = ContactForm(request.POST, request.FILES, instance=contact)
        if form.is_valid():
            contact = form.save(commit=False)
            contact.user = request.user
            contact.save()
            return HttpResponseRedirect(reverse('contacts:detail', args=(contact.id,)))
    else:
        form = ContactForm(instance=contact)
    return render(request, 'pages/contact_create.html', {'form': form, 'contact': contact})


@login_required(login_url="/login/")
def postcard_view(request, contact_id):
    contact = get_object_or_404(Contact, id=contact_id)
    send_postcard(contact)
    return HttpResponseRedirect(reverse('contacts:detail', args=(contact.id,)))

crm/contacts/templates/pages/contact_create.html
{% extends 'layouts/base.html' %}

{% block title %} Profile {% endblock title %}

{% block content %}

<!-- Header -->
<div class="header pb-8 pt-5 pt-lg-8 d-flex align-items-center" style="min-height: 50px; background-image: url(/static/assets/img/theme/profile-cover.jpg); background-size: cover; background-position: center top;">
  <!-- Mask -->
  <span class="mask bg-gradient-default opacity-8"></span>
  <!-- Header container -->
  <div class="container-fluid d-flex align-items-center">
    <div class="row">
      <div class="col-lg-7 col-md-10">
        <h1 class="display-2 text-white">{{ contact }}</h1>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid mt--7">
  <form method="post" enctype="multipart/form-data">
    <div class="row">
      <div class="col-xl-4 order-xl-2 mb-5 mb-xl-0">
        <div class="card card-profile shadow">
          <div class="row justify-content-center">
            <div class="col-lg-3 order-lg-2">
              <div class="card-profile-image">
                {% if contact.profile_picture != "" %}
                <img src="{{ contact.profile_picture.url }}" id="contact-image" class="rounded-circle" style="max-height:200px">
                {% else %}
                <img src="/static/assets/img/default-profile.png" class="rounded-circle">
                {% endif %}
              </div>
            </div>
          </div>
          <div class="card-header text-center border-0 pt-8 pt-md-4 pb-0 pb-md-4">
          </div>
          <div class="card-body pt-0 pt-md-4">
            <div class="row">
              <div class="col">
                <div class="card-profile-stats d-flex justify-content-center mt-md-5">
                </div>
              </div>
            </div>
            <div class="text-center">
              <div class="col text-center">
                {% csrf_token %}
                <input type="file" class="btn-sm" name="{{ form.profile_picture.name }}" id="{{ form.profile_picture.id_for_label }}" {% if form.profile_picture.field.required %}required{% endif %}>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-xl-8 order-xl-1">
        {% csrf_token %}
        <div class="card bg-secondary shadow">
          <div class="card-header bg-white border-0">
            <div class="row align-items-center">
              <div class="col-8">
                <h3 class="mb-0">Contact Details</h3>
              </div>
              <div class="col-4 text-right">
                <button type="submit" class="btn btn-sm btn-primary">Save</button>
              </div>
            </div>
          </div>
          <div class="card-body">
            <h6 class="heading-small text-muted mb-4">Contact information</h6>
            <div class="pl-lg-4">
              <div class="row">
                <div class="col-lg-6">
                  <div class="form-group">
                    <label class="form-control-label" for="input-first-name">First name</label>
                    <input type="text" class="form-control form-control-alternative" name="{{ form.first_name.name }}" id="{{ form.first_name.id_for_label }}" {% if form.first_name.value != None %}value="{{ form.first_name.value|stringformat:'s' }}"
                      {% endif %} maxlength="{{ form.first_name.field.max_length }}" {% if form.first_name.field.required %}required{% endif %}>

                  </div>
                </div>
                <div class="col-lg-6">
                  <div class="form-group">
                    <label class="form-control-label" for="input-last-name">Last name</label>
                    <input type="text" class="form-control form-control-alternative" name="{{ form.last_name.name }}" id="{{ form.last_name.id_for_label }}" {% if form.last_name.value != None %}value="{{ form.last_name.value|stringformat:'s' }}"
                      {% endif %} maxlength="{{ form.last_name.field.max_length }}" {% if form.last_name.field.required %}required{% endif %}>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-lg-12">
                  <div class="form-group">
                    <label class="form-control-label" for="input-email">Email address</label>
                    <input type="email" class="form-control form-control-alternative" name="{{ form.email.name }}" id="{{ form.email.id_for_label }}" {% if form.email.value != None %}value="{{ form.email.value|stringformat:'s' }}" {% endif %}
                      maxlength="{{ form.email.field.max_length }}" {% if form.email.field.required %}required{% endif %}>
                  </div>
                </div>
              </div>

            </div>
            <hr class="my-4" />
            <!-- Address -->
            <h6 class="heading-small text-muted mb-4">Address information</h6>
            <div class="pl-lg-4">
              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <label class="form-control-label" for="input-address-1">Address Line 1</label>
                    <input type="text" class="form-control form-control-alternative" name="{{ form.address_line_1.name }}" id="{{ form.address_line_1.id_for_label }}"
                      {% if form.address_line_1.value != None %}value="{{ form.address_line_1.value|stringformat:'s' }}" {% endif %} maxlength="{{ form.address_line_1.field.max_length }}"
                      {% if form.address_line_1.field.required %}required{% endif %}>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <label class="form-control-label" for="input-address-2">Address Line 2</label>
                    <input type="text" class="form-control form-control-alternative" name="{{ form.address_line_2.name }}" id="{{ form.address_line_2.id_for_label }}"
                      {% if form.address_line_2.value != None %}value="{{ form.address_line_2.value|stringformat:'s' }}" {% endif %} maxlength="{{ form.address_line_2.field.max_length }}"
                      {% if form.address_line_2.field.required %}required{% endif %}>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-lg-4">
                  <div class="form-group">
                    <label class="form-control-label" for="input-city">City</label>
                    <input type="text" class="form-control form-control-alternative" name="{{ form.city.name }}" id="{{ form.city.id_for_label }}" {% if form.city.value != None %}value="{{ form.city.value|stringformat:'s' }}" {% endif %}
                      maxlength="{{ form.city.field.max_length }}" {% if form.city.field.required %}required{% endif %}>
                  </div>
                </div>
                <div class="col-lg-4">
                  <div class="form-group">
                    <label class="form-control-label" for="input-state">state</label>
                    <input type="text" class="form-control form-control-alternative" name="{{ form.state.name }}" id="{{ form.state.id_for_label }}" {% if form.state.value != None %}value="{{ form.state.value|stringformat:'s' }}" {% endif %}
                      maxlength="{{ form.state.field.max_length }}" {% if form.state.field.required %}required{% endif %}>
                  </div>
                </div>
                <div class="col-lg-4">
                  <div class="form-group">
                    <label class="form-control-label" for="input-zipcode">Zipcode</label>
                    <input type="text" class="form-control form-control-alternative" name="{{ form.zipcode.name }}" id="{{ form.zipcode.id_for_label }}" {% if form.zipcode.value != None %}value="{{ form.zipcode.value|stringformat:'s' }}" {% endif %}
                      maxlength="{{ form.zipcode.field.max_length }}" {% if form.zipcode.field.required %}required{% endif %}>
                  </div>
                </div>
              </div>
            </div>
            <hr class="my-4" />
  </form>
</div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}{% endblock javascripts %}

crm/contacts/templates/pages/error-404.html
{% extends 'layouts/base-fullscreen.html' %}

{% block title %} Error 404 {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- Page content -->
    <div class="container mt--8 pb-5">
      <div class="row justify-content-center">
        <div class="col-lg-5 col-md-7">
          <div class="card bg-secondary shadow border-0">
            <div class="card-header bg-transparent pb-5">

              <div class="text-muted text-center mt-2 mb-3">
                Oups! Error 404
              </div>

              <div class="text-center mb-4">
                Page not found
              </div>

            </div>
          </div>
          <div class="row mt-3">
            <div class="col-6">
              <a href="/" class="text-light"><small>Home</small></a>
            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}{% endblock javascripts %}

crm/contacts/templates/pages/maps.html
{% extends 'layouts/base.html' %}

{% block title %} Maps {% endblock title %}

{% block content %}

    <!-- Header -->
    <div class="header bg-gradient-primary pb-8 pt-5 pt-md-8">
      <div class="container-fluid">
        <div class="header-body">
          <!-- Card stats -->
          <div class="row">
            <div class="col-xl-3 col-lg-6">
              <div class="card card-stats mb-4 mb-xl-0">
                <div class="card-body">
                  <div class="row">
                    <div class="col">
                      <h5 class="card-title text-uppercase text-muted mb-0">Traffic</h5>
                      <span class="h2 font-weight-bold mb-0">350,897</span>
                    </div>
                    <div class="col-auto">
                      <div class="icon icon-shape bg-danger text-white rounded-circle shadow">
                        <i class="fas fa-chart-bar"></i>
                      </div>
                    </div>
                  </div>
                  <p class="mt-3 mb-0 text-muted text-sm">
                    <span class="text-success mr-2"><i class="fa fa-arrow-up"></i> 3.48%</span>
                    <span class="text-nowrap">Since last month</span>
                  </p>
                </div>
              </div>
            </div>
            <div class="col-xl-3 col-lg-6">
              <div class="card card-stats mb-4 mb-xl-0">
                <div class="card-body">
                  <div class="row">
                    <div class="col">
                      <h5 class="card-title text-uppercase text-muted mb-0">New users</h5>
                      <span class="h2 font-weight-bold mb-0">2,356</span>
                    </div>
                    <div class="col-auto">
                      <div class="icon icon-shape bg-warning text-white rounded-circle shadow">
                        <i class="fas fa-chart-pie"></i>
                      </div>
                    </div>
                  </div>
                  <p class="mt-3 mb-0 text-muted text-sm">
                    <span class="text-danger mr-2"><i class="fas fa-arrow-down"></i> 3.48%</span>
                    <span class="text-nowrap">Since last week</span>
                  </p>
                </div>
              </div>
            </div>
            <div class="col-xl-3 col-lg-6">
              <div class="card card-stats mb-4 mb-xl-0">
                <div class="card-body">
                  <div class="row">
                    <div class="col">
                      <h5 class="card-title text-uppercase text-muted mb-0">Sales</h5>
                      <span class="h2 font-weight-bold mb-0">924</span>
                    </div>
                    <div class="col-auto">
                      <div class="icon icon-shape bg-yellow text-white rounded-circle shadow">
                        <i class="fas fa-users"></i>
                      </div>
                    </div>
                  </div>
                  <p class="mt-3 mb-0 text-muted text-sm">
                    <span class="text-warning mr-2"><i class="fas fa-arrow-down"></i> 1.10%</span>
                    <span class="text-nowrap">Since yesterday</span>
                  </p>
                </div>
              </div>
            </div>
            <div class="col-xl-3 col-lg-6">
              <div class="card card-stats mb-4 mb-xl-0">
                <div class="card-body">
                  <div class="row">
                    <div class="col">
                      <h5 class="card-title text-uppercase text-muted mb-0">Performance</h5>
                      <span class="h2 font-weight-bold mb-0">49,65%</span>
                    </div>
                    <div class="col-auto">
                      <div class="icon icon-shape bg-info text-white rounded-circle shadow">
                        <i class="fas fa-percent"></i>
                      </div>
                    </div>
                  </div>
                  <p class="mt-3 mb-0 text-muted text-sm">
                    <span class="text-success mr-2"><i class="fas fa-arrow-up"></i> 12%</span>
                    <span class="text-nowrap">Since last month</span>
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="container-fluid mt--7">

      <div class="row">
        <div class="col">
          <div class="card shadow border-0">
            <div id="map-canvas" class="map-canvas" data-lat="40.748817" data-lng="-73.985428" style="height: 600px;"></div>
          </div>
        </div>
      </div>

      {% include "includes/footer.html" %}

    </div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}{% endblock javascripts %}

crm/contacts/templates/pages/profile.html
{% extends 'layouts/base.html' %}

{% block title %} Profile {% endblock title %}

{% block content %}

    <!-- Header -->
    <div class="header pb-8 pt-5 pt-lg-8 d-flex align-items-center"
         style="min-height: 600px; background-image: url(/static/assets/img/theme/profile-cover.jpg); background-size: cover; background-position: center top;">
      <!-- Mask -->
      <span class="mask bg-gradient-default opacity-8"></span>
      <!-- Header container -->
      <div class="container-fluid d-flex align-items-center">
        <div class="row">
          <div class="col-lg-7 col-md-10">
            <h1 class="display-2 text-white">{{ contact }}</h1>
            <!-- <p class="text-white mt-0 mb-5">Contacts Page.asd fsa dfasdfa sdfsadf asdfsadfsa fsad fsadfadf as</p> -->
            <!-- <a href="#!" class="btn btn-info">Edit profile</a> -->
          </div>
        </div>
      </div>
    </div>

    <div class="container-fluid mt--7">

      <div class="row">
        <div class="col-xl-4 order-xl-2 mb-5 mb-xl-0">
          <div class="card card-profile shadow">
            <div class="row justify-content-center">
              <div class="col-lg-3 order-lg-2">
                <div class="card-profile-image">
                  {% if contact.profile_picture != "" %}
                  <img src="{{ contact.profile_picture.url }}" id="contact-image" class="rounded-circle" style="max-height:200px">
                  {% else %}
                  <img src="/static/assets/img/default-profile.png" class="rounded-circle">
                  {% endif %}
                </div>
              </div>
            </div>
            <div class="card-header text-center border-0 pt-8 pt-md-4 pb-0 pb-md-4">
              <!-- <div class="d-flex justify-content-between">
                <a href="#" class="btn btn-sm btn-info mr-4">Connect</a>
                <a href="#" class="btn btn-sm btn-default float-right">Message</a>
              </div> -->
            </div>
            <div class="card-body pt-0 pt-md-4">
              <div class="row">
                <div class="col">
                  <div class="card-profile-stats d-flex justify-content-center mt-md-5">
                    <!-- <div>
                      <span class="heading">22</span>
                      <span class="description">Friends</span>
                    </div>
                    <div>
                      <span class="heading">10</span>
                      <span class="description">Photos</span>
                    </div>
                    <div>
                      <span class="heading">89</span>
                      <span class="description">Comments</span>
                    </div> -->
                  </div>
                </div>
              </div>
              <div class="text-center">
                <form method='POST' enctype="multipart/form-data">
                  {% csrf_token %}
                <div class="pl-lg-4">
                  <div class="form-group">
                    <label>Send Postcard</label>
                    {% if postcard_error %}
                    <div class="alert alert-primary" role="alert">
                      {{ postcard_error }}
                    </div>
                    {% endif %}
                    {% if postcard_success %}
                    <div class="alert alert-success" role="alert">
                      Postcard sent!
                    </div>
                    {% endif %}
                    <textarea rows="4" name="postcard_text" class="form-control form-control-alternative" placeholder="Postcard text here"></textarea>
                  </div>
                </div>
                <div class="text-center">
                  <button type="submit" class="btn btn-sm btn-primary">Send a Postcard</button>
                  <br>


                  <!-- <br><br>
                  <h6 class="heading-small text-muted mb-4">(Make sure to save your changes first)</h6> -->
                  <!-- <h6 class="heading-small text-muted mb-4">success text goes here</h6> -->
                </div>
                </form>
                <!-- <h3>
                  {{ contact }}
                </h3>
                <div class="h5 font-weight-300">
                  {{ contact }}
                </div> -->
                <!-- <div class="h5 mt-4">
                  <i class="ni business_briefcase-24 mr-2"></i>Solution Manager - Creative Tim Officer
                </div>
                <div>
                  <i class="ni education_hat mr-2"></i>University of Computer Science
                </div>
                <hr class="my-4" />
                <p>Ryan — the name taken by Melbourne-raised, Brooklyn-based Nick Murphy — writes, performs and records all of his own music.</p>
                <a href="#">Show more</a> -->
              </div>
            </div>
          </div>
        </div>
        <div class="col-xl-8 order-xl-1">
          <div class="card bg-secondary shadow">
            <div class="card-header bg-white border-0">
              <div class="row align-items-center">
                <div class="col-8">
                  <h3 class="mb-0">Contact Details</h3>
                </div>
                <div class="col-4 text-right">
                  <a href="{% url 'contacts:edit' contact_id=contact.id %}" class="btn btn-sm btn-primary">Edit</a>
                </div>
              </div>
            </div>
            <div class="card-body">
              <form>
                <h6 class="heading-small text-muted mb-4">Contact information</h6>
                <div class="pl-lg-4">
                  <div class="row">
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-first-name">First name</label>
                        <input disabled type="text" id="input-first-name" class="form-control form-control-alternative"
                        value="{{ contact.first_name }}">
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-last-name">Last name</label>
                        <input disabled type="text" id="input-last-name" class="form-control form-control-alternative"
                        value="{{ contact.last_name }}">
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <!-- <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-username">Username</label>
                        <input disabled type="text" id="input-username" class="form-control form-control-alternative" placeholder="Username"
                               value="{{ request.user.username }}">
                      </div>
                    </div> -->
                    <div class="col-lg-12">
                      <div class="form-group">
                        <label class="form-control-label" for="input-email">Email address</label>
                        <input disabled type="email" id="input-email" class="form-control form-control-alternative"
                               value="{{ contact.email }}">
                      </div>
                    </div>
                  </div>

                </div>
                <hr class="my-4" />
                <!-- Address -->
                <h6 class="heading-small text-muted mb-4">Address information</h6>
                <div class="pl-lg-4">
                  <div class="row">
                    <div class="col-md-12">
                      <div class="form-group">
                        <label class="form-control-label" for="input-address">Address Line 1</label>
                        <input disabled id="address-line-1" class="form-control form-control-alternative" type="text" value="{{ contact.address_line_1 }}">
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-12">
                      <div class="form-group">
                        <label class="form-control-label" for="input-address">Address Line 2</label>
                        <input disabled id="address-line-2" class="form-control form-control-alternative" type="text" value="{{ contact.address_line_2 }}">
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-lg-4">
                      <div class="form-group">
                        <label class="form-control-label" for="input-city">City</label>
                        <input disabled type="text" id="input-city" class="form-control form-control-alternative" placeholder="City" value="{{ contact.city }}">
                      </div>
                    </div>
                    <div class="col-lg-4">
                      <div class="form-group">
                        <label class="form-control-label" for="input-country">State</label>
                        <input disabled type="text" id="input-country" class="form-control form-control-alternative" placeholder="State" value="{{ contact.state }}">
                      </div>
                    </div>
                    <div class="col-lg-4">
                      <div class="form-group">
                        <label class="form-control-label" for="input-country">Zipcode</label>
                        <input disabled type="number" id="input-postal-code" class="form-control form-control-alternative" placeholder="Zipcode" value="{{ contact.zipcode }}">
                      </div>
                    </div>

                  </div>
                </div>
                <hr class="my-4" />
                <!-- Description -->
                <!-- <h6 class="heading-small text-muted mb-4">About me</h6>
                <div class="pl-lg-4">
                  <div class="form-group">
                    <label>About Me</label>
                    <textarea rows="4" class="form-control form-control-alternative" placeholder="A few words about you ...">A beautiful Dashboard for Bootstrap 4. It is Free and Open Source.</textarea>
                  </div>
                </div> -->
              </form>
            </div>
          </div>
        </div>
      </div>

    </div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}{% endblock javascripts %}